### ISSUE TITLE
Global code review

### ISSUE THREAD

**Issue by antoinealb** [cvra/can-bootloader#21]
@Stapelzeiger said we should do a code review of the bootloader. Should we do it before it is finished ?

**Comment by msplr** [comment]
I'm for doing it before. It's more efficient.

**Comment by antoinealb** [comment]
Something formal ? Like printing the whole code and highlighting the "wrong" parts ? If we do something less formal we will need a volunteer !

**Comment by 31415us** [comment]
if you want i can help you with the code review (= (for example tomorrow)

**Comment by Stapelzeiger** [comment]
I'll review the code. I'll probably have time between Christmas and New-Year.
I was thinking about commenting the code and give you the diff. (I need ctags/search function since I'm not familiar with the codebase.)

**Comment by antoinealb** [comment]
I am ok with whatever method for code review. Maybe fork it and open a PR with your comment and fixes ?

**Comment by antoinealb** [comment]
any updates on this ?

**Comment by Stapelzeiger** [comment]
I couldn't find the time to do a full review. I only took a quick look at the code. On first impression it looks OK, but there are some checks missing.
I guess as soon as it works we should move to the next thing since we still have quite a lot to do. For a later version (next year) we should probably improve a few things and I'd still like to do a full review sometime, but it's currently not on my priority list.
