### ISSUE TITLE
Unused 'check write status' bootloader command

### ISSUE THREAD

**Issue by msplr** [cvra/can-bootloader#27]
There is no possibility to respond to a request from the client during flashing.
Therefore we should drop the command 5:

```
5. Check write status (0x05). Parameters: None. Returns: True if a write is currently in progress, False otherwise.
```

To check if the write was successful, one should send a 'compute CRC' or 'read flash' command for the written flash page.

**Comment by antoinealb** [comment]
So to know if the write was complete, one should spam the compute CRC commands until the board answers again ?

**Comment by msplr** [comment]
You're right. We need a sort of status command to check if the board is ready. 
So we should probably just rename the command to something like:

```
5. Ping (0x05). Parameters: None. Returns: True if bootloader is ready to accept a command.
```

**Comment by Stapelzeiger** [comment]
We could also let the bootloader respond with a _done_ upon completion of the flash command.

**Comment by msplr** [comment]
Not really, since we can't have n devices responding at the same time with done.
We only need to know if at least one device is done to continue flashing.
The case where one device misses a command is detected afterwards by crc.

**Comment by Stapelzeiger** [comment]
> Not really, since we can't have n devices responding at the same time with done.

why not?

> We only need to know if at least one device is done to continue flashing.

If we want to do broadcast we need to wait for all (or most) of them.

**Comment by 31415us** [comment]
i think this might be pretty orthongonal to the current discussion but i think a generalised 'ping' command which returns more than just a boolean but some status stuff could be pretty nice for debugging (sorry if this is too off topic^^)

edit: maybe ping with the id of the board as parameter and if none is given its a broadcast ping

**Comment by antoinealb** [comment]
@31415us We already have adressing, so we can choose between unicast or multicast ping. Broadcast is not supported, and won't be to keep the protocol simple.

Also we can't have n devices responding at the same time because we don't have proper bus arbitration / retransmit logic. I am against changing this, because it would make the protocol too complicated.

My vote goes for the ping command and active polling.

**Comment by 31415us** [comment]
@antoinealb ok^^ thanks for the clarification (=

**Comment by msplr** [comment]
@Stapelzeiger It is possible, though it is quite probable to loose packets if ~50 devices saturate the bus by responding at the same time with 2 packets each.

> If we want to do broadcast we need to wait for all (or most) of them.

If we flash a firmware, it is always on identical devices, so they will all need the same time, which makes misses quite improbable.

After all, I thought that we wanted to keep the flashing process simple.
I'm for checking only one device for finishing the page write, add a minimal delay and continue flashing until it's done. Then we check each board individually for errors.

**Comment by antoinealb** [comment]
The other option would be to wait for a single  board, quickly check every other, and proceed with the flashing. Much safer, not much longer.

**Comment by Stapelzeiger** [comment]
> If we flash a firmware, it is always on identical devices, so they will all need the same time, which makes misses quite improbable.

datasheet says there is a factor of two possible (20 to 40ms)

I'm ok with a ping (but as a multicast, since we run on python through a serial-can bridge and thus might have quite high latency)

Concerning the arbitration loss / transmission error, we really should handle that. It's like two lines of code: just loop until your packet goes out without errors or the loop-counter reaches a defined maximum.
